# Continuos Integration workflow for ensuring the code follows the code conventions
name: Format CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

        # Get the codebase but only incude the history of 5 commits instead of the entire history
      - run: git fetch --no-tags --prune --depth=5 origin ${{ github.event.pull_request.base.ref }}
        # Install the apps using npm ci (ensures a clean install)
      - run: npm ci
      - run: npm run format:check -- --base=origin/${{ github.event.pull_request.base.ref }}
